### ISSUE TITLE
Hierarchical Parts/Chapters

### ISSUE THREAD

**Issue by xaeiougit** [KrumpetPirate/AAXtoMP3#184] opened 2021-12-14 02:17 UTC
Some books on audible have Parts and Chapters.  The JSON chapter file generated by audible-cli might look like this:

{
    "content_metadata": {
        "chapter_info": {
            "brandIntroDurationMs": 1532,
            "brandOutroDurationMs": 3204,

            "chapters": [
                {
                    "length_ms": 16578,
                    "start_offset_ms": 0,
                    "start_offset_sec": 0,
                    "title": "Opening Credits"
                },

                {
                    "chapters": [
                        {
                            "length_ms": 4296073,
                            "start_offset_ms": 3768168,
                            "start_offset_sec": 3768,
                            "title": "1 A Long expected Party "
                        },
                       # lots more chapter stanzas deleted
                        {
                            "length_ms": 3609356,
                            "start_offset_ms": 37514546,
                            "start_offset_sec": 37515,
                            "title": "12 Flight to the Ford "
                        }
                    ],
                    "length_ms": 3101,
                    "start_offset_ms": 3765067,
                    "start_offset_sec": 3765,
                    "title": "Book I: "
                },

Currently when AAXtoMP3 encounters this, chapter markers for "Opening Credits" and "Book I:" are created.  However,  there are no markers for chapters inside Part "Book I":  "1 A Long expected Party " and "12 Flight to the Ford ".

Even tho this is a hierarchy, all the offsets are still relative to the start of the file, and the lengths of the Parts are short i.e. do not cover the lengths of all the Chapters they contain.  So everything is really just a marker, and it might be reasonable to create chapter markers for all.  If you split chapters into separate files this might result in short empty files for Parts, but this shouldn't break anything.

The parsing black magic for "jq" definitely makes my head spin:
`
jq -r \
        'def pad(n): tostring | if (n > length) then ((n - length) * "0") + . else . end;
        .content_metadata.chapter_info.chapters |
        to_entries |
        .[] |
        "CHAPTER\((.key))=\(((.value.start_offset_ms / (1000*60*60)) %24 | floor | pad(2))):\(((.value.start_offset_ms / (1000*60)) %60 | floor | pad(2))):\(((.value.start_offset_ms / 1000) %60 | floor | pad(2))).\((.value.start_offset_ms % 1000 | pad(3)))
CHAPTER\((.key))NAME=\(.value.title)"' "${extra_chapter_file}" > "${tmp_chapter_file}"
`

I'm willing to look at this some more to try and figure it out, but thought I'd raise this issue first and get some feedback on whether this is a current limitation, and not some problem specific to my environment.

**Comment by njmdietrich** [comment] 2022-02-06 20:35
I can confirm that this is an issue. Nested parts/chapters result in the vast majority of the book missing in the output, probably because only the "top-level" length is considered when creating the chapter files. In principle, I agree that the easiest fix for this would be to just flatten the hierarchy and treat everything as a "top-level" chapter. I wonder whether this would lead to issues, though, in the case that sub-chapters have the same title as other sub-chapters in different parts?

**Closed** 2022-03-02 18:14 UTC
